import './globals.css'
import type { Metadata } from 'next'
import { Jost } from 'next/font/google'
import Navbar from './components/navigation/Navbar'
import Chatbot from './components/elements/Chatbot'
import { ReduxProvider } from '@/redux/provider'

const jost = Jost({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={jost.className}>
        <ReduxProvider>
          <Navbar />
          {children}
          <Chatbot />
        </ReduxProvider>
      </body>
    </html>
  )
}
