import './globals.css'
import type { Metadata } from 'next'
import { Jost } from 'next/font/google'
import Navbar from './components/navigation/Navbar'
import { Provider } from 'react-redux'
import { store } from './store/store'

const jost = Jost({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={jost.className}>
        <Provider store={store}>
          <Navbar />
          {children}
        </Provider>
      </body>
    </html>
  )
}
